<?php

namespace Database\Seeders;

use App\Models\KiosBank\ProductKiosBank;
use Illuminate\Database\Seeder;

class ProductKiosBankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            [ 'id' => 1, 'kategori' => 'WIFI ID', 'sub_kategori' => 'PULSA', 'kode' => '502001', 'name' => 'WIFI ID 20.000', 'prefix_id' => null],
            [ 'id' => 2, 'kategori' => 'WIFI ID', 'sub_kategori' => 'PULSA', 'kode' => '505001', 'name' => 'WIFI ID 50.000', 'prefix_id' => null],
            [ 'id' => 3, 'kategori' => 'INDOSAT', 'sub_kategori' => 'PULSA', 'kode' => '500511', 'name' => 'INDOSAT PRABAYAR 5.000', 'prefix_id' => 11],
            [ 'id' => 4, 'kategori' => 'INDOSAT', 'sub_kategori' => 'PULSA', 'kode' => '501011', 'name' => 'INDOSAT PRABAYAR 10.000', 'prefix_id' => 11],
            [ 'id' => 5, 'kategori' => 'INDOSAT', 'sub_kategori' => 'PULSA', 'kode' => '502511', 'name' => 'INDOSAT PRABAYAR 25.000', 'prefix_id' => 11],
            [ 'id' => 6, 'kategori' => 'INDOSAT', 'sub_kategori' => 'PULSA', 'kode' => '505011', 'name' => 'INDOSAT PRABAYAR 50.000', 'prefix_id' => 11],
            [ 'id' => 7, 'kategori' => 'INDOSAT', 'sub_kategori' => 'PULSA', 'kode' => '510011', 'name' => 'INDOSAT PRABAYAR 100.000', 'prefix_id' => 11],
            [ 'id' => 8, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D0111', 'name' => 'INDOSAT DATA 1GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 9, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D0211', 'name' => 'INDOSAT DATA 2GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 10, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D0311', 'name' => 'INDOSAT DATA 3GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 11, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D0511', 'name' => 'INDOSAT DATA 5 GB 30 HARI', 'prefix_id' => 11],
            [ 'id' => 12, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D0711', 'name' => '100MB', 'prefix_id' => 11],
            [ 'id' => 13, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D0811', 'name' => '200MB', 'prefix_id' => 11],
            [ 'id' => 14, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D0911', 'name' => 'INDOSAT DATA 300MB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 15, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D1011', 'name' => 'INDOSAT DATA 500MB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 16, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D1111', 'name' => '700MB', 'prefix_id' => 11],
            [ 'id' => 17, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D1211', 'name' => '1GB', 'prefix_id' => 11],
            [ 'id' => 18, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D1511', 'name' => 'INDOSAT DATA 4GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 19, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D2911', 'name' => 'INTERNET UNLIMITED + 10GB, 30 HARI', 'prefix_id' => 11],
            [ 'id' => 20, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D4311', 'name' => 'PAKET YELLOW INTERNET 1GB 15 HARI', 'prefix_id' => 11],
            [ 'id' => 21, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D4411', 'name' => 'PAKET YELLOW INTERNET 1GB 1 HARI', 'prefix_id' => 11],
            [ 'id' => 22, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D4511', 'name' => 'PAKET YELLOW INTERNET 1GB 3 HARI', 'prefix_id' => 11],
            [ 'id' => 23, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D4611', 'name' => 'INDOSAT DATA 750MB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 24, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D4711', 'name' => 'INDOSAT DATA 1,5GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 25, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D4811', 'name' => 'INDOSAT DATA 2,5GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 26, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D4911', 'name' => 'INDOSAT DATA 6GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 27, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D5011', 'name' => 'INDOSAT DATA 7GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 28, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D5111', 'name' => 'INDOSAT DATA 8GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 29, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D5211', 'name' => 'INDOSAT DATA 9GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 30, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D5311', 'name' => 'INDOSAT DATA 10GB 24 JAM 30 HR', 'prefix_id' => 11],
            [ 'id' => 31, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D5811', 'name' => 'INDOSAT DATA FREEDOM 2GB', 'prefix_id' => 11],
            [ 'id' => 32, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D5911', 'name' => 'INDOSAT DATA FREEDOM 4GB', 'prefix_id' => 11],
            [ 'id' => 33, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D6011', 'name' => 'INDOSAT DATA FREEDOM 7,5GB', 'prefix_id' => 11],
            [ 'id' => 34, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D6111', 'name' => 'INDOSAT DATA FREEDOM 11GB', 'prefix_id' => 11],
            [ 'id' => 35, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D6211', 'name' => 'INDOSAT DATA FREEDOM 16GB', 'prefix_id' => 11],
            [ 'id' => 36, 'kategori' => 'INDOSAT', 'sub_kategori' => 'Paket Data', 'kode' => '5D6311', 'name' => 'INDOSAT DATA FREEDOM 25GB', 'prefix_id' => 11],
            [ 'id' => 37, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'PULSA', 'kode' => '500521', 'name' => 'TELKOMSEL PRABAYAR 5.000', 'prefix_id' => 21],
            [ 'id' => 38, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'PULSA', 'kode' => '501021', 'name' => 'TELKOMSEL PRABAYAR 10.000', 'prefix_id' => 21],
            [ 'id' => 39, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'PULSA', 'kode' => '502021', 'name' => 'TELKOMSEL PRABAYAR 20.000', 'prefix_id' => 21],
            [ 'id' => 40, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'PULSA', 'kode' => '502521', 'name' => 'TELKOMSEL PRABAYAR 25.000', 'prefix_id' => 21],
            [ 'id' => 41, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'PULSA', 'kode' => '505021', 'name' => 'TELKOMSEL PRABAYAR 50.000', 'prefix_id' => 21],
            [ 'id' => 42, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'PULSA', 'kode' => '510021', 'name' => 'TELKOMSEL PRABAYAR 100.000', 'prefix_id' => 21],
            [ 'id' => 43, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D0421', 'name' => 'TELKOMSEL DATA MINI 1GB 7HR', 'prefix_id' => 21],
            [ 'id' => 44, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1221', 'name' => '50MB - 110MB SESUAI ZONA', 'prefix_id' => 21],
            [ 'id' => 45, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1421', 'name' => '1 GB SEMUA JARINGAN + BEBAS ZONA', 'prefix_id' => 21],
            [ 'id' => 46, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1521', 'name' => '200MB - 420MB SESUAI ZONA', 'prefix_id' => 21],
            [ 'id' => 47, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1621', 'name' => '50 GB + 2GB VIDEOMAX', 'prefix_id' => 21],
            [ 'id' => 48, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1721', 'name' => '360MB - 800MB SESUAI ZONA', 'prefix_id' => 21],
            [ 'id' => 49, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1821', 'name' => '2 GB SEMUA JARINGAN + BEBAS ZONA', 'prefix_id' => 21],
            [ 'id' => 50, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1921', 'name' => '3 GB SEMUA JARINGAN + BEBAS ZONA', 'prefix_id' => 21],
            [ 'id' => 51, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2021', 'name' => '20MB - 40MB SESUAI ZONA', 'prefix_id' => 21],
            [ 'id' => 52, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2121', 'name' => '800MB - 1.5GB SESUAI ZONA', 'prefix_id' => 21],
            [ 'id' => 53, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2221', 'name' => '500 MB SEMUA JARINGAN + BEBAS ZONA', 'prefix_id' => 21],
            [ 'id' => 54, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2321', 'name' => '750 MB SEMUA JARINGAN + BEBAS ZONA', 'prefix_id' => 21],
            [ 'id' => 55, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2721', 'name' => '12 GB VIDEOMAX, 30 HARI', 'prefix_id' => 21],
            [ 'id' => 56, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2821', 'name' => 'TSEL DATA 750 MB FLASH 30 HR', 'prefix_id' => 21],
            [ 'id' => 57, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2921', 'name' => 'TSEL DATA 1GB FLASH 30 HR', 'prefix_id' => 21],
            [ 'id' => 58, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3021', 'name' => 'TSEL DATA 2GB FLASH 30 HR', 'prefix_id' => 21],
            [ 'id' => 59, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3121', 'name' => 'TSEL DATA 3GB FLASH 30 HR', 'prefix_id' => 21],
            [ 'id' => 60, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3221', 'name' => 'TSEL DATA 4GB FLASH 30 HR', 'prefix_id' => 21],
            [ 'id' => 61, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3321', 'name' => 'TSEL DATA 8GB FLASH 30 HR', 'prefix_id' => 21],
            [ 'id' => 62, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3421', 'name' => 'TSEL DATA 50 MB 7 HR', 'prefix_id' => 21],
            [ 'id' => 63, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3521', 'name' => 'TSEL DATA 100 MB 7 HR', 'prefix_id' => 21],
            [ 'id' => 64, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3621', 'name' => 'TSEL DATA 250 MB 30 HR', 'prefix_id' => 21],
            [ 'id' => 65, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3721', 'name' => 'TSEL DATA 500 MB 30 HR', 'prefix_id' => 21],
            [ 'id' => 66, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3821', 'name' => 'TSEL DATA 2 GB 30 HR', 'prefix_id' => 21],
            [ 'id' => 67, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3921', 'name' => 'TSEL DATA 4 GB 30 HR', 'prefix_id' => 21],
            [ 'id' => 68, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4021', 'name' => 'TELKOMSEL DATA MINI 1GB 1HR', 'prefix_id' => 21],
            [ 'id' => 69, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4121', 'name' => 'TELKOMSEL DATA MINI 1GB ALL 3HR', 'prefix_id' => 21],
            [ 'id' => 70, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4221', 'name' => 'TELKOMSEL DATA MINI 2GB ALL 3HR', 'prefix_id' => 21],
            [ 'id' => 71, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4321', 'name' => 'TELKOMSEL DATA MINI 2GB ALL 7HR', 'prefix_id' => 21],
            [ 'id' => 72, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4521', 'name' => 'TELKOMSEL DATA MINI 3GB ALL 3HR', 'prefix_id' => 21],
            [ 'id' => 73, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4621', 'name' => 'TELKOMSEL DATA MINI 3GB ALL 7HR', 'prefix_id' => 21],
            [ 'id' => 74, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4821', 'name' => 'TELKOMSEL DATA MINI 5GB ALL 3HR', 'prefix_id' => 21],
            [ 'id' => 75, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4921', 'name' => 'TELKOMSEL DATA MINI 5GB ALL 7HR', 'prefix_id' => 21],
            [ 'id' => 76, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D5121', 'name' => 'TELKOMSEL DATA MINI 10GB ALL 3HR', 'prefix_id' => 21],
            [ 'id' => 77, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D5221', 'name' => 'TELKOMSEL DATA MINI 10GB ALL 7HR', 'prefix_id' => 21],
            [ 'id' => 78, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'Paket Data', 'kode' => '5D5321', 'name' => 'TELKOMSEL DATA MINI 2GB,ALL,14 HARI', 'prefix_id' => 21],
            [ 'id' => 79, 'kategori' => 'XL', 'sub_kategori' => 'PULSA', 'kode' => '500531', 'name' => 'XL PRABAYAR 5.000', 'prefix_id' => 31],
            [ 'id' => 80, 'kategori' => 'XL', 'sub_kategori' => 'PULSA', 'kode' => '501031', 'name' => 'XL PRABAYAR 10.000', 'prefix_id' => 31],
            [ 'id' => 81, 'kategori' => 'XL', 'sub_kategori' => 'PULSA', 'kode' => '502531', 'name' => 'XL PRABAYAR 25.000', 'prefix_id' => 31],
            [ 'id' => 82, 'kategori' => 'XL', 'sub_kategori' => 'PULSA', 'kode' => '505031', 'name' => 'XL PRABAYAR 50.000', 'prefix_id' => 31],
            [ 'id' => 83, 'kategori' => 'XL', 'sub_kategori' => 'PULSA', 'kode' => '510031', 'name' => 'XL PRABAYAR 100.000', 'prefix_id' => 31],
            [ 'id' => 84, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D0931', 'name' => 'XL INTERNET HOTROD 24JAM 6GB 30HR', 'prefix_id' => 31],
            [ 'id' => 85, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1031', 'name' => 'XL INTERNET HOTROD 24JAM 800MB 30HR', 'prefix_id' => 31],
            [ 'id' => 86, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1131', 'name' => 'XL INTERNET HOTROD 24JAM 3GB 30HR', 'prefix_id' => 31],
            [ 'id' => 87, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1231', 'name' => 'XL INTERNET HOTROD 24JAM 8GB 30HR', 'prefix_id' => 31],
            [ 'id' => 88, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1431', 'name' => 'XL INTERNET HOTROD 24JAM 12GB 30HR', 'prefix_id' => 31],
            [ 'id' => 89, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1531', 'name' => 'XL INTERNET HOTROD 24JAM 16GB 30HR', 'prefix_id' => 31],
            [ 'id' => 90, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1631', 'name' => 'XTRA COMBO VIP 5GB+5GB, 30 HARI', 'prefix_id' => 31],
            [ 'id' => 91, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1731', 'name' => 'XTRA COMBO VIP 10GB+10GB, 30 HARI', 'prefix_id' => 31],
            [ 'id' => 92, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1831', 'name' => 'XTRA COMBO VIP 15GB+15GB, 30 HARI', 'prefix_id' => 31],
            [ 'id' => 93, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D1931', 'name' => 'XTRA COMBO VIP 20GB+20GB, 30 HARI', 'prefix_id' => 31],
            [ 'id' => 94, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2031', 'name' => 'XTRA COMBO VIP 35GB+35GB, 30 HARI', 'prefix_id' => 31],
            [ 'id' => 95, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2531', 'name' => 'XTRA COMBO 5GB+5GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 96, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2631', 'name' => 'XTRA COMBO 10GB+10GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 97, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2731', 'name' => 'XTRA COMBO 15GB+15GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 98, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2831', 'name' => 'XTRA COMBO 20GB+20GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 99, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D2931', 'name' => 'XTRA COMBO 35GB+35GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 100, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3031', 'name' => 'XTRA COMBO 15GB+15GB, 30HR', 'prefix_id' => 31],
            [ 'id' => 101, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3131', 'name' => 'XTRA COMBO 18GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 102, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3231', 'name' => 'XTRA COMBO 20GB+20GB, 30HR', 'prefix_id' => 31],
            [ 'id' => 103, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3331', 'name' => 'XTRA COMBO 30GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 104, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3431', 'name' => 'XTRA COMBO 35GB+35GB, 30HR', 'prefix_id' => 31],
            [ 'id' => 105, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3531', 'name' => 'XTRA COMBO 42GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 106, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3731', 'name' => 'XTRA COMBO 5GB+5GB, 30HR', 'prefix_id' => 31],
            [ 'id' => 107, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3831', 'name' => 'XTRA COMBO 6GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 108, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D3931', 'name' => 'XTRA COMBO 10GB+10GB, 30HR', 'prefix_id' => 31],
            [ 'id' => 109, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4031', 'name' => 'XTRA COMBO 12GB - 12 BULAN', 'prefix_id' => 31],
            [ 'id' => 110, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4231', 'name' => 'XTRA BICARA NELPON + INTERNET 30 HARI', 'prefix_id' => 31],
            [ 'id' => 111, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4431', 'name' => 'XL INTERNET HOTROD 24JAM 1GB 7HR', 'prefix_id' => 31],
            [ 'id' => 112, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4531', 'name' => 'XL DATA 2,5GB NAS + 2GB MALAM + 1,5GB LOKAL', 'prefix_id' => 31],
            [ 'id' => 113, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4631', 'name' => 'XL DATA 6GB NAS + 1GB MALAM + 3GB LOKAL 30HR', 'prefix_id' => 31],
            [ 'id' => 114, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4731', 'name' => 'XTRA COMBO LITE 13GB 30 HR', 'prefix_id' => 31],
            [ 'id' => 115, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4831', 'name' => 'XL DATA 6GB LOKAL  ZONA) +26GB NASIONAL XXL 30HR', 'prefix_id' => 31],
            [ 'id' => 116, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D4931', 'name' => 'XL DATA 37GB NAS + 7GB LOKAL  ZONA) 30HR', 'prefix_id' => 31],
            [ 'id' => 117, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D5031', 'name' => 'XL DATA COMBO 5GB', 'prefix_id' => 31],
            [ 'id' => 118, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D5131', 'name' => 'XL DATA COMBO 10GB', 'prefix_id' => 31],
            [ 'id' => 119, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D5231', 'name' => 'XL DATA COMBO 15GB', 'prefix_id' => 31],
            [ 'id' => 120, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D5331', 'name' => 'XL DATA COMBO 20GB', 'prefix_id' => 31],
            [ 'id' => 121, 'kategori' => 'XL', 'sub_kategori' => 'Paket Data', 'kode' => '5D5431', 'name' => 'XL DATA COMBO 35GB', 'prefix_id' => 31],
            [ 'id' => 122, 'kategori' => 'THREE', 'sub_kategori' => 'PULSA', 'kode' => '500541', 'name' => 'THREE PRABAYAR 5.000', 'prefix_id' => null],
            [ 'id' => 123, 'kategori' => 'THREE', 'sub_kategori' => 'PULSA', 'kode' => '501041', 'name' => 'THREE PRABAYAR 10.000', 'prefix_id' => null],
            [ 'id' => 124, 'kategori' => 'THREE', 'sub_kategori' => 'PULSA', 'kode' => '502041', 'name' => 'THREE PRABAYAR 20.000', 'prefix_id' => null],
            [ 'id' => 125, 'kategori' => 'THREE', 'sub_kategori' => 'PULSA', 'kode' => '502541', 'name' => 'THREE PRABAYAR 25.000', 'prefix_id' => null],
            [ 'id' => 126, 'kategori' => 'THREE', 'sub_kategori' => 'PULSA', 'kode' => '505041', 'name' => 'THREE PRABAYAR 50.000', 'prefix_id' => null],
            [ 'id' => 127, 'kategori' => 'THREE', 'sub_kategori' => 'PULSA', 'kode' => '510041', 'name' => 'THREE PRABAYAR 100.000', 'prefix_id' => null],
            [ 'id' => 128, 'kategori' => 'THREE', 'sub_kategori' => 'Paket Data', 'kode' => '5D1141', 'name' => 'INTERNET 100GB, 7 HARI', 'prefix_id' => null],
            [ 'id' => 129, 'kategori' => 'THREE', 'sub_kategori' => 'Paket Data', 'kode' => '5D1441', 'name' => 'MIX SUPER 10GB', 'prefix_id' => null],
            [ 'id' => 130, 'kategori' => 'THREE', 'sub_kategori' => 'Paket Data', 'kode' => '5D1541', 'name' => 'MIX SUPER 30GB', 'prefix_id' => null],
            [ 'id' => 131, 'kategori' => 'THREE', 'sub_kategori' => 'Paket Data', 'kode' => '5D1741', 'name' => 'MIX SMALL 3.75GB (1.75GB + 2GB 4G)', 'prefix_id' => null],
            [ 'id' => 132, 'kategori' => 'THREE', 'sub_kategori' => 'Paket Data', 'kode' => '5D1941', 'name' => 'MIX SMALL 2.75GB (750MB + 2GB 4G)', 'prefix_id' => null],
            [ 'id' => 133, 'kategori' => 'THREE', 'sub_kategori' => 'Paket Data', 'kode' => '5D2041', 'name' => 'MIX SMALL 3GB', 'prefix_id' => null],
            [ 'id' => 134, 'kategori' => 'AXIS', 'sub_kategori' => 'PULSA', 'kode' => '500551', 'name' => 'AXIS PRABAYAR 5.000', 'prefix_id' => null],
            [ 'id' => 135, 'kategori' => 'AXIS', 'sub_kategori' => 'PULSA', 'kode' => '501051', 'name' => 'AXIS PRABAYAR 10.000', 'prefix_id' => null],
            [ 'id' => 136, 'kategori' => 'AXIS', 'sub_kategori' => 'PULSA', 'kode' => '502551', 'name' => 'AXIS PRABAYAR 25.000', 'prefix_id' => null],
            [ 'id' => 137, 'kategori' => 'AXIS', 'sub_kategori' => 'PULSA', 'kode' => '505051', 'name' => 'AXIS PRABAYAR 50.000', 'prefix_id' => null],
            [ 'id' => 138, 'kategori' => 'AXIS', 'sub_kategori' => 'PULSA', 'kode' => '510051', 'name' => 'AXIS PRABAYAR 100.000', 'prefix_id' => null],
            [ 'id' => 139, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D0151', 'name' => 'AXIS PAKET BRONET 1GB 24JAM 30 HARI', 'prefix_id' => null],
            [ 'id' => 140, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D0251', 'name' => 'BRONET 2GB, 60 HARI', 'prefix_id' => null],
            [ 'id' => 141, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D0351', 'name' => 'BRONET 3GB, 60 HARI', 'prefix_id' => null],
            [ 'id' => 142, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D0451', 'name' => 'BRONET 5GB, 60 HARI', 'prefix_id' => null],
            [ 'id' => 143, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D2751', 'name' => 'AXIS PAKET BRONET 300MB 24JAM 7 HARI', 'prefix_id' => null],
            [ 'id' => 144, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D2851', 'name' => 'AXIS PAKET BRONET 2GB 24JAM 30 HARI', 'prefix_id' => null],
            [ 'id' => 145, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D2951', 'name' => 'AXIS PAKET BRONET 3GB 24JAM 30 HARI', 'prefix_id' => null],
            [ 'id' => 146, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D3051', 'name' => 'AXIS PAKET BRONET 5GB 24JAM 30 HARI', 'prefix_id' => null],
            [ 'id' => 147, 'kategori' => 'AXIS', 'sub_kategori' => 'Paket Data', 'kode' => '5D3151', 'name' => 'AXIS PAKET BRONET 8GB 24JAM 30 HARI', 'prefix_id' => null],
            [ 'id' => 148, 'kategori' => 'ESIA', 'sub_kategori' => 'PULSA', 'kode' => '500561', 'name' => 'ESIA PRABAYAR 5.000', 'prefix_id' => null],
            [ 'id' => 149, 'kategori' => 'FLEXI', 'sub_kategori' => 'PULSA', 'kode' => '500571', 'name' => 'FLEXI PRABAYAR 5.000', 'prefix_id' => null],
            [ 'id' => 150, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'PULSA', 'kode' => '500581', 'name' => 'SMARTFREN PRABAYAR 5.000', 'prefix_id' => null],
            [ 'id' => 151, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'PULSA', 'kode' => '501081', 'name' => 'SMARTFREN PRABAYAR 10.000', 'prefix_id' => null],
            [ 'id' => 152, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'PULSA', 'kode' => '502081', 'name' => 'SMARTFREN PRABAYAR 20.000', 'prefix_id' => null],
            [ 'id' => 153, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'PULSA', 'kode' => '502581', 'name' => 'SMARTFREN PRABAYAR 25.000', 'prefix_id' => null],
            [ 'id' => 154, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'PULSA', 'kode' => '505081', 'name' => 'SMARTFREN PRABAYAR 50.000', 'prefix_id' => null],
            [ 'id' => 155, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'PULSA', 'kode' => '510081', 'name' => 'SMARTFREN PRABAYAR 100.000', 'prefix_id' => null],
            [ 'id' => 156, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D0181', 'name' => 'INTERNET 10RB', 'prefix_id' => null],
            [ 'id' => 157, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D0281', 'name' => 'INTERNET 20RB', 'prefix_id' => null],
            [ 'id' => 158, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D0381', 'name' => 'INTERNET 30RB', 'prefix_id' => null],
            [ 'id' => 159, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D0481', 'name' => 'INTERNET 60RB', 'prefix_id' => null],
            [ 'id' => 160, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D0581', 'name' => 'INTERNET 100RB', 'prefix_id' => null],
            [ 'id' => 161, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D0681', 'name' => 'INTERNET 150RB', 'prefix_id' => null],
            [ 'id' => 162, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D0781', 'name' => 'INTERNET 200RB', 'prefix_id' => null],
            [ 'id' => 163, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D1481', 'name' => 'SMARTFREN DATA 4GB', 'prefix_id' => null],
            [ 'id' => 164, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D1581', 'name' => 'SMARTFREN DATA 6GB', 'prefix_id' => null],
            [ 'id' => 165, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D1681', 'name' => 'SMARTFREN DATA 10GB', 'prefix_id' => null],
            [ 'id' => 166, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D1781', 'name' => 'PAKET VOLUME BASED 16GB', 'prefix_id' => null],
            [ 'id' => 167, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D1981', 'name' => 'SMARTFREN DATA 90GB', 'prefix_id' => null],
            [ 'id' => 168, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'Paket Data', 'kode' => '5D2081', 'name' => 'SMARTFREN DATA 120GB', 'prefix_id' => null],
            [ 'id' => 169, 'kategori' => 'TELKOMSEL', 'sub_kategori' => 'PULSA PASCABAYAR', 'kode' => '520021', 'name' => 'HALO', 'prefix_id' => null],
            [ 'id' => 170, 'kategori' => 'XL', 'sub_kategori' => 'PULSA PASCABAYAR', 'kode' => '550041', 'name' => 'XPLOR', 'prefix_id' => null],
            [ 'id' => 171, 'kategori' => 'THREE', 'sub_kategori' => 'PULSA PASCABAYAR', 'kode' => '550071', 'name' => 'TRI PASCABAYAR', 'prefix_id' => null],
            [ 'id' => 172, 'kategori' => 'INDOSAT', 'sub_kategori' => 'PULSA PASCABAYAR', 'kode' => '550081', 'name' => 'INDOSAT (MATRIX)', 'prefix_id' => null],
            [ 'id' => 173, 'kategori' => 'SMARTFREN', 'sub_kategori' => 'PULSA PASCABAYAR', 'kode' => '560031', 'name' => 'SMART / FREN / HEPI / MOBI', 'prefix_id' => null],
            [ 'id' => 174, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751021', 'name' => 'OVO 25.000', 'prefix_id' => null],
            [ 'id' => 175, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751031', 'name' => 'OVO 50.000', 'prefix_id' => null],
            [ 'id' => 176, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751041', 'name' => 'OVO 100.000', 'prefix_id' => null],
            [ 'id' => 177, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751051', 'name' => 'OVO 200.000', 'prefix_id' => null],
            [ 'id' => 178, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751061', 'name' => 'OVO 300.000', 'prefix_id' => null],
            [ 'id' => 179, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751071', 'name' => 'OVO 500.000', 'prefix_id' => null],
            [ 'id' => 180, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751081', 'name' => 'OVO 30.000', 'prefix_id' => null],
            [ 'id' => 181, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751091', 'name' => 'OVO 40.000', 'prefix_id' => null],
            [ 'id' => 182, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751101', 'name' => 'OVO 75.000', 'prefix_id' => null],
            [ 'id' => 183, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751111', 'name' => 'OVO 150.000', 'prefix_id' => null],
            [ 'id' => 184, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751121', 'name' => 'OVO 250.000', 'prefix_id' => null],
            [ 'id' => 185, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751131', 'name' => 'OVO 400.000', 'prefix_id' => null],
            [ 'id' => 186, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751501', 'name' => 'GRAB DRIVER 10.000', 'prefix_id' => null],
            [ 'id' => 187, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751511', 'name' => 'GRAB DRIVER 20.000', 'prefix_id' => null],
            [ 'id' => 188, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751521', 'name' => 'GRAB DRIVER 25.000', 'prefix_id' => null],
            [ 'id' => 189, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751531', 'name' => 'GRAB DRIVER 50.000', 'prefix_id' => null],
            [ 'id' => 190, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751541', 'name' => 'GRAB DRIVER 100.000', 'prefix_id' => null],
            [ 'id' => 191, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751551', 'name' => 'GRAB DRIVER 150.000', 'prefix_id' => null],
            [ 'id' => 192, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751561', 'name' => 'GRAB DRIVER 200.000', 'prefix_id' => null],
            [ 'id' => 193, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751571', 'name' => 'GRAB DRIVER 300.000', 'prefix_id' => null],
            [ 'id' => 194, 'kategori' => 'OVO', 'sub_kategori' => 'Uang Elektronik', 'kode' => '751581', 'name' => 'GRAB DRIVER 500.000', 'prefix_id' => null],
            [ 'id' => 195, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752011', 'name' => 'TOPUP GOPAY 50.000', 'prefix_id' => null],
            [ 'id' => 196, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752021', 'name' => 'TOPUP GOPAY 25.000', 'prefix_id' => null],
            [ 'id' => 197, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752031', 'name' => 'TOPUP GOPAY 100.000', 'prefix_id' => null],
            [ 'id' => 198, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752041', 'name' => 'TOPUP GOPAY 250.000', 'prefix_id' => null],
            [ 'id' => 199, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752051', 'name' => 'TOPUP GOPAY 200.000', 'prefix_id' => null],
            [ 'id' => 200, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752061', 'name' => 'TOPUP GOPAY 5.000', 'prefix_id' => null],
            [ 'id' => 201, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752081', 'name' => 'TOPUP GOPAY 10.000', 'prefix_id' => null],
            [ 'id' => 202, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752091', 'name' => 'TOPUP GOPAY 15.000', 'prefix_id' => null],
            [ 'id' => 203, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752101', 'name' => 'TOPUP GOPAY 30.000', 'prefix_id' => null],
            [ 'id' => 204, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752111', 'name' => 'TOPUP GOPAY 40.000', 'prefix_id' => null],
            [ 'id' => 205, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752121', 'name' => 'TOPUP GOPAY 75.000', 'prefix_id' => null],
            [ 'id' => 206, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752131', 'name' => 'TOPUP GOPAY 150.000', 'prefix_id' => null],
            [ 'id' => 207, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752141', 'name' => 'TOPUP GOPAY 300.000', 'prefix_id' => null],
            [ 'id' => 208, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752151', 'name' => 'TOPUP GOPAY 500.000', 'prefix_id' => null],
            [ 'id' => 209, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752161', 'name' => 'TOPUP GOPAY 1.000.000', 'prefix_id' => null],
            [ 'id' => 210, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752501', 'name' => 'TOPUP GOJEK (DRIVER) 20.000', 'prefix_id' => null],
            [ 'id' => 211, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752511', 'name' => 'TOPUP GOJEK (DRIVER) 50.000', 'prefix_id' => null],
            [ 'id' => 212, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752521', 'name' => 'TOPUP GOJEK (DRIVER) 75.000', 'prefix_id' => null],
            [ 'id' => 213, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752531', 'name' => 'TOPUP GOJEK (DRIVER) 100.000', 'prefix_id' => null],
            [ 'id' => 214, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752541', 'name' => 'TOPUP GOJEK (DRIVER) 150.000', 'prefix_id' => null],
            [ 'id' => 215, 'kategori' => 'GOPAY', 'sub_kategori' => 'Uang Elektronik', 'kode' => '752551', 'name' => 'TOPUP GOJEK (DRIVER) 200.000', 'prefix_id' => null],
            [ 'id' => 216, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756011', 'name' => 'SHOPEE PAY 20.000', 'prefix_id' => null],
            [ 'id' => 217, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756021', 'name' => 'SHOPEE PAY 25.000', 'prefix_id' => null],
            [ 'id' => 218, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756031', 'name' => 'SHOPEE PAY 30.000', 'prefix_id' => null],
            [ 'id' => 219, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756041', 'name' => 'SHOPEE PAY 40.000', 'prefix_id' => null],
            [ 'id' => 220, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756051', 'name' => 'SHOPEE PAY 50.000', 'prefix_id' => null],
            [ 'id' => 221, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756061', 'name' => 'SHOPEE PAY 60.000', 'prefix_id' => null],
            [ 'id' => 222, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756071', 'name' => 'SHOPEE PAY 70.000', 'prefix_id' => null],
            [ 'id' => 223, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756081', 'name' => 'SHOPEE PAY 75.000', 'prefix_id' => null],
            [ 'id' => 224, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756091', 'name' => 'SHOPEE PAY 80.000', 'prefix_id' => null],
            [ 'id' => 225, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756101', 'name' => 'SHOPEE PAY 90.000', 'prefix_id' => null],
            [ 'id' => 226, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756111', 'name' => 'SHOPEE PAY 100.000', 'prefix_id' => null],
            [ 'id' => 227, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756121', 'name' => 'SHOPEE PAY 150.000', 'prefix_id' => null],
            [ 'id' => 228, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756131', 'name' => 'SHOPEE PAY 200.000', 'prefix_id' => null],
            [ 'id' => 229, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756141', 'name' => 'SHOPEE PAY 250.000', 'prefix_id' => null],
            [ 'id' => 230, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756151', 'name' => 'SHOPEE PAY 300.000', 'prefix_id' => null],
            [ 'id' => 231, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756161', 'name' => 'SHOPEE PAY 400.000', 'prefix_id' => null],
            [ 'id' => 232, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756171', 'name' => 'SHOPEE PAY 500.000', 'prefix_id' => null],
            [ 'id' => 233, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756181', 'name' => 'SHOPEE PAY 600.000', 'prefix_id' => null],
            [ 'id' => 234, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756191', 'name' => 'SHOPEE PAY 700.000', 'prefix_id' => null],
            [ 'id' => 235, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756201', 'name' => 'SHOPEE PAY 800.000', 'prefix_id' => null],
            [ 'id' => 236, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756211', 'name' => 'SHOPEE PAY 900.000', 'prefix_id' => null],
            [ 'id' => 237, 'kategori' => 'SHOPEE PAY ', 'sub_kategori' => 'Uang Elektronik', 'kode' => '756221', 'name' => 'SHOPEE PAY 1000.000', 'prefix_id' => null],
            [ 'id' => 238, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755011', 'name' => 'LINKAJA 15.000', 'prefix_id' => null],
            [ 'id' => 239, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755021', 'name' => 'LINKAJA 20.000', 'prefix_id' => null],
            [ 'id' => 240, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755031', 'name' => 'LINKAJA 25.000', 'prefix_id' => null],
            [ 'id' => 241, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755041', 'name' => 'LINKAJA 30.000', 'prefix_id' => null],
            [ 'id' => 242, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755051', 'name' => 'LINKAJA 35.000', 'prefix_id' => null],
            [ 'id' => 243, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755061', 'name' => 'LINKAJA 40.000', 'prefix_id' => null],
            [ 'id' => 244, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755071', 'name' => 'LINKAJA 45.000', 'prefix_id' => null],
            [ 'id' => 245, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755081', 'name' => 'LINKAJA 50.000', 'prefix_id' => null],
            [ 'id' => 246, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755091', 'name' => 'LINKAJA 55.000', 'prefix_id' => null],
            [ 'id' => 247, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755101', 'name' => 'LINKAJA 60.000', 'prefix_id' => null],
            [ 'id' => 248, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755111', 'name' => 'LINKAJA 70.000', 'prefix_id' => null],
            [ 'id' => 249, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755121', 'name' => 'LINKAJA 75.000', 'prefix_id' => null],
            [ 'id' => 250, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755131', 'name' => 'LINKAJA 80.000', 'prefix_id' => null],
            [ 'id' => 251, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755141', 'name' => 'LINKAJA 85.000', 'prefix_id' => null],
            [ 'id' => 252, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755151', 'name' => 'LINKAJA 90.000', 'prefix_id' => null],
            [ 'id' => 253, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755161', 'name' => 'LINKAJA 95.000', 'prefix_id' => null],
            [ 'id' => 254, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755171', 'name' => 'LINKAJA 100.000', 'prefix_id' => null],
            [ 'id' => 255, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755181', 'name' => 'LINKAJA 125.000', 'prefix_id' => null],
            [ 'id' => 256, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755191', 'name' => 'LINKAJA 150.000', 'prefix_id' => null],
            [ 'id' => 257, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755201', 'name' => 'LINKAJA 175.000', 'prefix_id' => null],
            [ 'id' => 258, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755211', 'name' => 'LINKAJA 200.000', 'prefix_id' => null],
            [ 'id' => 259, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755221', 'name' => 'LINKAJA 250.000', 'prefix_id' => null],
            [ 'id' => 260, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755231', 'name' => 'LINKAJA 300.000', 'prefix_id' => null],
            [ 'id' => 261, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755241', 'name' => 'LINKAJA 500.000', 'prefix_id' => null],
            [ 'id' => 262, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755251', 'name' => 'LINKAJA 400.000', 'prefix_id' => null],
            [ 'id' => 263, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755261', 'name' => 'LINKAJA 600.000', 'prefix_id' => null],
            [ 'id' => 264, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755271', 'name' => 'LINKAJA 700.000', 'prefix_id' => null],
            [ 'id' => 265, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755281', 'name' => 'LINKAJA 800.000', 'prefix_id' => null],
            [ 'id' => 266, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755291', 'name' => 'LINKAJA 900.000', 'prefix_id' => null],
            [ 'id' => 267, 'kategori' => 'LINK AJA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '755301', 'name' => 'LINKAJA 1.000.000', 'prefix_id' => null],
            [ 'id' => 268, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754011', 'name' => 'TOPUP SALDO DANA 15.000', 'prefix_id' => null],
            [ 'id' => 269, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754021', 'name' => 'TOPUP SALDO DANA 20.000', 'prefix_id' => null],
            [ 'id' => 270, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754031', 'name' => 'TOPUP SALDO DANA 25.000', 'prefix_id' => null],
            [ 'id' => 271, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754041', 'name' => 'TOPUP SALDO DANA 50.000', 'prefix_id' => null],
            [ 'id' => 272, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754061', 'name' => 'TOPUP SALDO DANA 100.000', 'prefix_id' => null],
            [ 'id' => 273, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754071', 'name' => 'TOPUP SALDO DANA 200.000', 'prefix_id' => null],
            [ 'id' => 274, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754081', 'name' => 'TOPUP SALDO DANA 300.000', 'prefix_id' => null],
            [ 'id' => 275, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754091', 'name' => 'TOPUP SALDO DANA 400.000', 'prefix_id' => null],
            [ 'id' => 276, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754101', 'name' => 'TOPUP SALDO DANA 500.000', 'prefix_id' => null],
            [ 'id' => 277, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754111', 'name' => 'TOPUP SALDO DANA 600.000', 'prefix_id' => null],
            [ 'id' => 278, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754121', 'name' => 'TOPUP SALDO DANA 700.000', 'prefix_id' => null],
            [ 'id' => 279, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754131', 'name' => 'TOPUP SALDO DANA 800.000', 'prefix_id' => null],
            [ 'id' => 280, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754141', 'name' => 'TOPUP SALDO DANA 900.000', 'prefix_id' => null],
            [ 'id' => 281, 'kategori' => 'DANA', 'sub_kategori' => 'Uang Elektronik', 'kode' => '754151', 'name' => 'TOPUP SALDO DANA 1.000.000', 'prefix_id' => null],
        ];

        foreach ($data as $key => $value) {
            ProductKiosBank::updateOrCreate([
                'kode' => $value['kode'],
            ],$value);
        }
        
    }
}
