<!DOCTYPE html>
<html>
    <head>
        <title>This Email generated by {{ config('app.name', 'Laravel') }}</title>
    </head>

    <body>
        <h1>Test Send Email</h1>
        <p>This Email generated by {{ config('app.name', 'Laravel') }}</p>
        <p>Thank you</p>
    </body>

</html>
